[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_API_BASE_URL = "https://erdalguda.online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 